version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: Scripts/dc.sh
    - location: Scripts/dc1.sh
  AfterInstall:
    - location: Scripts/dc2.sh
      timeout: 180
  ApplicationStart:
    - location: Scripts/dc3.sh
      timeout: 3600
  ValidateService:
    - location: Scripts/dc4.sh
      timeout: 3600
      runas: codedeployuser
